### ISSUE TITLE
handle none

### ISSUE THREAD

**Issue by NinDTendo** [NinDTendo/dori#2]
```Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 865, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1327, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/dori/binary_sensor.py", line 67, in async_added_to_hass
    self.update()
  File "/config/custom_components/dori/binary_sensor.py", line 98, in update
    self.get_next_event_start(entity_id)
  File "/config/custom_components/dori/binary_sensor.py", line 77, in get_next_event_start
    start_time = self.hass.states.get(entity_id).attributes.get("start_time")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'attributes'```

handle none on startup.

**Comment by NinDTendo** [comment]
```
Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:576
integration: Binary sensor (documentation, issues)
First occurred: 4:25:52 AM (1 occurrences)
Last logged: 4:25:52 AM

Error adding entity binary_sensor.day_of_rest_dat for domain binary_sensor with platform dori
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 865, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1327, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/dori/binary_sensor.py", line 67, in async_added_to_hass
    self.update()
  File "/config/custom_components/dori/binary_sensor.py", line 98, in update
    self.get_next_event_start(entity_id)
  File "/config/custom_components/dori/binary_sensor.py", line 77, in get_next_event_start
    start_time = self.hass.states.get(entity_id).attributes.get("start_time")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'attributes'

```
